# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- main

pool:
  vmImage: ubuntu-latest
  name: Self Hosted Agents

steps: 
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Go Get - Download Go packages and their dependencies'
- task: Go@0
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Go Build - Builds the Go application'
- task: CopyFiles@2
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Create artificats'
- task: PublishBuildArtifacts@1
  inputs:
     artifactName: drop
  displayName: 'Publish Artifacts'
